### PR TITLE
[WIP] Implement ICEBreakerV1.0e

### PR DESCRIPTION
**Pull request by TurBoss**
Hello,

Awesome project!

I just have an icebreaker around and wanted to try but I'm getting out of ideas when building the Firmware

I gert this error

```

make
python3 buildtool.py configs/ICEBreakerV1.0e/config.json
%Warning-WIDTH: plugins/vout_sinepwm/vout_sinepwm.v:29:31: Bit extraction of array[29:0] requires 5 bit index, not 8 bits.
                                                         : ... In instance vout_sinepwm
   29 |                 dty = sine_tbl[cnt];
      |                               ^
                ... Use "/* verilator lint_off WIDTH */" and lint_on around source to disable this message.
%Error: Exiting due to 1 warning(s)
generating files in Output/ICEBreakerV1.0e
generating qtgui
generating firmware
generating linux-cnc config
generating linux-cnc component
generating doc
(cd Output/ICEBreakerV1.0e/Firmware/ ; make)
make[1]: se entra en el directorio '/home/turboss/Projects/LinuxCNC-RIO/Output/ICEBreakerV1.0e/Firmware'
yosys -q -l yosys.log -p 'synth_ice40 -top rio -json rio.json' vin_frequency.v vout_pwm.v vin_pwmcounter.v vin_pulsecounter.v quad_encoder.v joint_stepper.v joint_stepper_nf.v expansion_shiftreg.v interface_spislave.v joint_rcservo.v vin_quadencoder.v vout_sinepwm.v vin_sonar.v vout_frequency.v debouncer.v rio.v
Warning: reg '\DIR' is assigned in a continuous assignment at vout_frequency.v:11.12-11.33.
nextpnr-ice40 -q -l nextpnr.log --up5k --package sg48 --json rio.json --pcf pins.pcf --asc rio.asc
ERROR: package does not have a pin named 'CLK' (on line 2)
ERROR: Loading PCF failed.
0 warnings, 2 errors
make[1]: *** [Makefile:12: rio.asc] Error 255
make[1]: se sale del directorio '/home/turboss/Projects/LinuxCNC-RIO/Output/ICEBreakerV1.0e/Firmware'
make: *** [Makefile:38: firmware] Error 2
```

what I'm missing? (sure lot of things :-)

Thank you

### CODE REVIEW

**Comment by multigcs** [comment]
Hi and Welcome :)
its all fine, but you need to add the real pin names to config.json not the board-pin names:

CLK -> 35
P1_B1 -> 43
....

**Comment by TurBoss** [comment]
great that worked thank you so much

**Comment by multigcs** [comment]
`
{
    "name": "ICEBreakerV1.0e",
    "description": "only for testing",
    "toolchain": "icestorm",
    "family": "ice40",
    "type": "up5k",
    "package": "sg48",
    "clock": {
        "speed": "120000000",
        "pin": "35"
    },
    "interface": [
    	{
	        "type": "spi",
	        "pins": {
	            "MOSI": "43",
	            "MISO": "38",
	            "SCK": "34",
	            "SEL": "31"
	        }
    	}
   ],
    "din": [
        {
            "debounce": true,
            "pin": "101"
        },
        {
            "debounce": true,
            "pin": "102"
        },
        {
            "debounce": true,
            "pin": "103"
        }
    ],
    "dout": [
        {
            "pin": "LED0"
        },
        {
            "pin": "26"
        },
        {
            "pin": "27"
        }
    ],
    "vin": [
        {
            "type": "frequency",
            "pin": "P1A_10",
            "pullup": true
        }
    ],
    "vout": [
        {
            "type": "pwm",
            "pin": "25",
            "invert_pwm": true
        }
    ],
    "joints": [
        {
            "comment": "J9.1+3+4",
            "type": "stepper",
            "cl": false,
            "pins": {
                "dir": "4",
                "step": "2",
                "enable": "47"
            }
        },
        {
            "comment": "J9.1+3+4_2",
            "type": "stepper",
            "cl": false,
            "pins": {
                "dir": "45",
                "step": "P1_A5",
                "enable": "P1_A6"
            }
        },
        {
            "comment": "J9.1+3+4_3",
            "type": "stepper",
            "cl": false,
            "pins": {
                "dir": "3",
                "step": "48",
                "enable": "46"
            }
        }
    ]
}
`

**Comment by multigcs** [comment]
please ask if something is unclear and there will be a lot still unclear since you are the first one who tries to use it

connection to the rasperry: please use SPI CE_1 for the chip select

the buildtool generates a qt_spitest.py in the Firmware folder, you can use it to test the functions and the connection

**Comment by multigcs** [comment]
many thanks :)

**Comment by TurBoss** [comment]
yes done thank you!

now I'm fighting with feedback errors but another issue

**Comment by multigcs** [comment]
closed-loop setup will not really work at the moment,
if the problem is without encoders, then first try it  with less speed.
Another Problem can be a connection-problem on the spi-bus (loo long cables / bitrate to high / can be changed in rio.c)

**Comment by multigcs** [comment]
i think i found the problem:
change this in  rio.h:
#define PRU_BASEFREQ        120000
to this:
#define PRU_BASEFREQ        200000

i think i have to rewrite the complete hal-component,
this is only a modified version of the remora hal

**Pull request merged**
